name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run actionlint
        uses: ./.github/actions/actionlint

  lint-status:
    name: Lint GitHub Actions
    if: always()
    needs:
      - actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate actionlint result
        run: |
          if [[ "${{ needs.actionlint.result }}" != "success" && "${{ needs.actionlint.result }}" != "skipped" ]]; then
            echo "actionlint result: ${{ needs.actionlint.result }}" >&2
            exit 1
          fi
